name: Terraform CI

on:
  push:
    branches: ["master"]
    paths:
      - 'terraform/modules/**/*.tf'
      - '.github/workflows/**'
  pull_request:
    branches: ["master", "dev", "feature-*"]
    paths:
      - 'terraform/modules/**/*.tf'
      - '.github/workflows/**'
      
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        shell: bash
        # Set the working directory for all run steps
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Configure AWS credentials for Terraform operations
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.JAHID_GITHUB_CI_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.JAHID_GITHUB_CI_SECRET_KEY_ID }}
        aws-region: eu-west-2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false
      