name: Terraform CI

on:
  push:
    branches: ["master"]
    paths:
      - 'terraform/modules/**/*.tf'
      - '.github/workflows/**'
  pull_request:
    branches: ["master", "dev", "feature-*"]
    paths:
      - 'terraform/modules/**/*.tf'
      - '.github/workflows/**'

jobs:
  terraform:
    name: Terraform Static Analysis and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform/modules/test  # Adjust as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec for static security analysis
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./terraform/modules/test
          format: sarif
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tfsec SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: tflint --init && tflint

      - name: Terraform Plan
        run: terraform plan -no-color